Repository FATEC-SJC-NoName/back-chat-app, pull requests merged in 2020-10, with the labels that each got.

#2 Feature/messages
  .github/workflows/gradle.yml
  README.md
  build.gradle
  src/main/java/com/fatec/chatapp/messages/MessageModule.java
  src/main/java/com/fatec/chatapp/messages/MessagesController.java
  src/main/java/com/fatec/chatapp/messages/MessagesRepository.java
  src/main/java/com/fatec/chatapp/messages/MessagesService.java
  src/main/java/com/fatec/chatapp/messages/MessagesServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/fatec/chatapp/ChatAppApplicationTests.java
  src/test/java/com/fatec/chatapp/MessagesTests.java
Labels: enhancement

#5 Criação do módulo user
  src/main/java/com/fatec/chatapp/users/UserController.java
  src/main/java/com/fatec/chatapp/users/UserModule.java
  src/main/java/com/fatec/chatapp/users/UserRepository.java
  src/main/java/com/fatec/chatapp/users/UserService.java
  src/main/java/com/fatec/chatapp/users/UserServiceImpl.java
Labels: enhancement

#7 Sprint 2
  .github/workflows/gradle.yml
  README.md
  bin/.gitignore
  build.gradle
  src/main/java/com/fatec/chatapp/chats/ChatModel.java
  src/main/java/com/fatec/chatapp/chats/ChatsController.java
  src/main/java/com/fatec/chatapp/chats/ChatsRepository.java
  src/main/java/com/fatec/chatapp/chats/ChatsService.java
  src/main/java/com/fatec/chatapp/chats/ChatsServiceImpl.java
  src/main/java/com/fatec/chatapp/messages/MessageModel.java
  src/main/java/com/fatec/chatapp/messages/MessagesController.java
  src/main/java/com/fatec/chatapp/messages/MessagesRepository.java
  src/main/java/com/fatec/chatapp/messages/MessagesService.java
  src/main/java/com/fatec/chatapp/messages/MessagesServiceImpl.java
  src/main/java/com/fatec/chatapp/users/UserController.java
  src/main/java/com/fatec/chatapp/users/UserModule.java
  src/main/java/com/fatec/chatapp/users/UserRepository.java
  src/main/java/com/fatec/chatapp/users/UserService.java
  src/main/java/com/fatec/chatapp/users/UserServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/fatec/chatapp/ChatAppApplicationTests.java
  src/test/java/com/fatec/chatapp/ChatsTests.java
  src/test/java/com/fatec/chatapp/MessagesTests.java
Labels: enhancement

#17 Feature/Relashionship - WIP
  .github/workflows/sonar-scan.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/fatec/chatapp/chats/ChatModel.java
  src/main/java/com/fatec/chatapp/chats/ChatsController.java
  src/main/java/com/fatec/chatapp/chats/ChatsRepository.java
  src/main/java/com/fatec/chatapp/chats/ChatsService.java
  src/main/java/com/fatec/chatapp/chats/ChatsServiceImpl.java
  src/main/java/com/fatec/chatapp/config/SwaggerConfig.java
  src/main/java/com/fatec/chatapp/messages/MessageDTO.java
  src/main/java/com/fatec/chatapp/messages/MessageModel.java
  src/main/java/com/fatec/chatapp/messages/MessagesController.java
  src/main/java/com/fatec/chatapp/messages/MessagesServiceImpl.java
  src/main/java/com/fatec/chatapp/participants/ParticipantDTO.java
  src/main/java/com/fatec/chatapp/participants/ParticipantModel.java
  src/main/java/com/fatec/chatapp/participants/ParticipantsController.java
  src/main/java/com/fatec/chatapp/participants/ParticipantsServiceImpl.java
  src/main/java/com/fatec/chatapp/users/UserController.java
  src/main/java/com/fatec/chatapp/users/UserModel.java
  src/main/java/com/fatec/chatapp/users/UserService.java
  src/main/java/com/fatec/chatapp/users/UserServiceImpl.java
  src/main/java/com/fatec/chatapp/users/UsersController.java
  src/main/java/com/fatec/chatapp/users/UsersRepository.java
  src/main/java/com/fatec/chatapp/users/UsersService.java
  src/main/java/com/fatec/chatapp/users/UsersServiceImpl.java
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/test/java/com/fatec/chatapp/ChatsTests.java
  src/test/java/com/fatec/chatapp/MessagesTests.java
  src/test/java/com/fatec/chatapp/ParticipantsTests.java
Labels: enhancement, help wanted

#23 cors config
  src/main/java/com/fatec/chatapp/ChatAppApplication.java
  src/main/java/com/fatec/chatapp/config/WebConfig.java
Labels: enhancement

#24 fix done
  src/main/java/com/fatec/chatapp/chats/ChatModel.java
  src/test/java/com/fatec/chatapp/ChatsTests.java
Labels: bug

#31 remove fields from json
  src/main/java/com/fatec/chatapp/chats/ChatModel.java
  src/main/java/com/fatec/chatapp/messages/MessageModel.java
  src/main/java/com/fatec/chatapp/users/UserModel.java
Labels: enhancement
